// <auto-generated />
namespace HinesSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddingUserAndBlogpostConnectionBack : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingUserAndBlogpostConnectionBack));
        
        string IMigrationMetadata.Id
        {
            get { return "201407181321410_AddingUserAndBlogpostConnectionBack"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
